# Generated by Django 3.0.6 on 2020-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potato.jpg', upload_to='profile_pics'),
        ),
    ]
